# Generated by Django 5.2.4 on 2025-08-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="ai_model",
        ),
        migrations.RemoveField(
            model_name="message",
            name="response_time",
        ),
        migrations.RemoveField(
            model_name="message",
            name="token_count",
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(
                choices=[("USER", "User"), ("BOT", "Bot"), ("SYSTEM", "System")],
                max_length=10,
            ),
        ),
    ]
