# Generated by Django 5.2.4 on 2025-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("USER", "User"), ("BOT", "Bot")],
                default="ADMIN",
                max_length=50,
            ),
        ),
    ]
